### ISSUE TITLE
Fin du processus

### ISSUE THREAD

**Issue by amark97** [WinStryke/PaletteRGB#1]
Hello.

Lors de la fermeture de ta fenetre tu kill pas le processus, ce qui fait que malgres la dispartion de la fenetre ton processus tourne toujours, et si on a lance ton programme en cli (java PaletteRGB), on est oblige de balancer un ctrl + c en plus de la fermeture de la fenetre ce qui est problematique.

Pour arranger cela, il te suffit d'ajouter une ligne dans le constructeur de ta palette 

`

    public Palette(){
        controle = new Controleur();
        view = new Vue();
        view.setVisible(true);
        view.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mod = new Modele();
    }
`

**view.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);** qui est un setter. Je te laisse te documenter sur ca.

enjoy ;)

**Comment by WinStryke** [comment]
On l'a vu cette semaine mais anyway je le kill dans l'IDE de toute façon. Thx, j'add ça

**Comment by amark97** [comment]
Effectivement il faudra que tu commit, c'est vraiment pas negligeable, que tu coupes le process de x manieres differentes ou non ca revient a dire que lorsque l'utilisateur 'clique sur la croix' pour terminer ton programme, et bien il ne le termine pas...

Y'a aussi le fait que ton programme lance sa window derriere celles deja ouvertes au lieu de le faire en premier plan (du moins sur mac os), mais j'ai pas eu le temps de regarder ca... 
Peut etre du cote des JDialog qui sont preferables aux JView => [http://docs.oracle.com/javase/7/docs/api/javax/swing/JDialog.html](voir la doc)

Good luck ;)
